[package]
name = "scryr-cli-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
ron = "0.8.1"
serde = { version = "1.0.217", features = ["derive"] }
strum = "0.26.3"
strum_macros = "0.26.4"
url = "2.5.4"
