[project]
name = "scryr-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "devtools>=0.12.2",
    "pydantic>=2.10.5",
    "pydantic-extra-types>=2.10.2",
    "ruff>=0.9.2",
    "semver>=3.0.3",
]
